# Generated by Django 5.1.4 on 2025-01-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name_bn', models.TextField(blank=True, null=True)),
                ('cat_name_en', models.TextField(blank=True, null=True)),
                ('no_of_subcat', models.IntegerField(blank=True, null=True)),
                ('no_of_dua', models.IntegerField(blank=True, null=True)),
                ('cat_icon', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dua_name_bn', models.TextField(blank=True, null=True)),
                ('dua_name_en', models.TextField(blank=True, null=True)),
                ('top_bn', models.TextField(blank=True, null=True)),
                ('top_en', models.TextField(blank=True, null=True)),
                ('dua_arabic', models.TextField(blank=True, null=True)),
                ('dua_indopak', models.TextField(blank=True, null=True)),
                ('clean_arabic', models.TextField(blank=True, null=True)),
                ('transliteration_bn', models.TextField(blank=True, null=True)),
                ('transliteration_en', models.TextField(blank=True, null=True)),
                ('translation_bn', models.TextField(blank=True, null=True)),
                ('translation_en', models.TextField(blank=True, null=True)),
                ('bottom_bn', models.TextField(blank=True, null=True)),
                ('bottom_en', models.TextField(blank=True, null=True)),
                ('refference_bn', models.TextField(blank=True, null=True)),
                ('refference_en', models.TextField(blank=True, null=True)),
                ('audio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dua',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcat_name_bn', models.TextField(blank=True, null=True)),
                ('subcat_name_en', models.TextField(blank=True, null=True)),
                ('no_of_dua', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_category',
                'managed': False,
            },
        ),
    ]
